# -*- coding: utf-8 -*-
"""QuickCart_Stockout_Risk_Project_rutu shah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YJHerxN4m4N5soGfRCSZKKe4Nd0q37Ts
"""

import pandas as pd

stores = pd.read_csv(
    "dim_stores.csv",
    na_values=["N/A", "missing", "--", "NA", "null"],
    keep_default_na=True
)

skus = pd.read_csv(
    "dim_skus.csv",
    na_values=["N/A", "missing", "--", "NA", "null"],
    keep_default_na=True
)

suppliers = pd.read_csv(
    "dim_suppliers.csv",
    na_values=["N/A", "missing", "--", "NA", "null"],
    keep_default_na=True
)

events = pd.read_csv(
    "dim_events.csv",
    na_values=["N/A", "missing", "--", "NA", "null"],
    keep_default_na=True
)

inventory = pd.read_csv(
    "fact_inventory_daily.csv",
    na_values=["N/A", "missing", "--", "NA", "null"],
    keep_default_na=True
)

print("Stores:", stores.shape)
print("SKUs:", skus.shape)
print("Suppliers:", suppliers.shape)
print("Events:", events.shape)
print("Inventory:", inventory.shape)

print("Target distribution:")
print(inventory["stockout_risk"].value_counts())

print("\nDate range:")
print(inventory["date"].min(), "to", inventory["date"].max())
print("Unique dates:", inventory["date"].nunique())

print("\nMissing values:")
print(inventory.isna().sum())

inventory = inventory.merge(
    stores,
    on="store_id",
    how="left"
)

inventory = inventory.merge(
    skus.drop(columns=["supplier_id"]),
    on="sku_id",
    how="left"
)

inventory = inventory.merge(
    suppliers,
    on="supplier_id",
    how="left"
)

inventory = inventory.merge(
    events,
    on="date",
    how="left"
)

print("Final shape:", inventory.shape)

# Sanity checks from the project specification

print("Festival week effect:")
print(
    inventory.groupby("is_festival_week")["stockout_risk"]
    .apply(lambda x: (x == "Imminent").mean() * 100)
)

print("\nSupplier reliability effect:")
inventory["reliability_band"] = "High"

inventory.loc[
    inventory["reliability_score"] < 0.75,
    "reliability_band"
] = "Low"

inventory.loc[
    (inventory["reliability_score"] >= 0.75) &
    (inventory["reliability_score"] < 0.85),
    "reliability_band"
] = "Mid"


print(
    inventory.groupby("reliability_band", observed=True)["stockout_risk"]
    .apply(lambda x: (x == "Imminent").mean() * 100)
)

print("\nPerishable effect:")
print(
    inventory.groupby("is_perishable")["stockout_risk"]
    .apply(lambda x: (x == "Imminent").mean() * 100)
)

# Standardize city names
inventory["city_display"] = inventory["city_display"].str.title()

# Clean supplier reliability
inventory["reliability_score"] = pd.to_numeric(
    inventory["reliability_score"],
    errors="coerce"
)

inventory["supplier_reliability_clean"] = (
    inventory.groupby("category")["reliability_score"]
    .transform(lambda x: x.fillna(x.median()))
)

# Feature engineering
inventory["reorder_gap"] = (
    inventory["reorder_point"] - inventory["closing_stock"]
)

inventory["days_of_cover_ratio"] = (
    inventory["days_of_cover"] / inventory["lead_time_days_expected"]
)

inventory["day_of_month"] = pd.to_datetime(
    inventory["date"]
).dt.day

inventory["days_since_festival_start"] = (
    pd.to_datetime(inventory["date"])
    - pd.Timestamp("2026-10-22")
).dt.days

# Recent reorder
inventory = inventory.sort_values(
    ["store_id", "sku_id", "date"]
)

inventory["is_recent_reorder"] = (
    inventory.groupby(["store_id", "sku_id"])["reorder_placed"]
    .shift(1)
    .eq("Y")
    .astype(int)
)

print("Feature engineering complete.")

print(inventory[
    [
        "reorder_gap",
        "days_of_cover_ratio",
        "supplier_reliability_clean",
        "is_recent_reorder",
        "day_of_month",
        "days_since_festival_start"
    ]
].head())

print("\nMissing values in new features:")
print(inventory[
    [
        "reorder_gap",
        "days_of_cover_ratio",
        "supplier_reliability_clean",
        "is_recent_reorder",
        "day_of_month",
        "days_since_festival_start"
    ]
].isna().sum())

train = inventory[
    inventory["date"] < "2026-10-24"
].copy()

test = inventory[
    inventory["date"] >= "2026-10-24"
].copy()

print("Training shape:", train.shape)
print("Test shape:", test.shape)

from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score

X_train = train.drop(columns=["stockout_risk"])
y_train = train["stockout_risk"]

X_test = test.drop(columns=["stockout_risk"])
y_test = test["stockout_risk"]

baseline = DummyClassifier(strategy="most_frequent")
baseline.fit(X_train.select_dtypes(include="number"), y_train)

baseline_pred = baseline.predict(
    X_test.select_dtypes(include="number")
)

print("Baseline accuracy:", accuracy_score(y_test, baseline_pred))

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, accuracy_score

features = [
    "opening_stock",
    "units_demanded",
    "units_sold",
    "closing_stock",
    "reorder_point",
    "lead_time_days_expected",
    "sales_velocity_7d",
    "days_of_cover",
    "is_festival_week",
    "reorder_gap",
    "days_of_cover_ratio",
    "supplier_reliability_clean",
    "is_recent_reorder",
    "day_of_month",
    "days_since_festival_start",
    "category",
    "city_tier",
    "store_size",
    "is_perishable",
    "festive_relevant",
    "popularity_tier"
]

X_train = train[features]
X_test = test[features]

categorical_features = [
    "is_festival_week",
    "category",
    "city_tier",
    "store_size",
    "is_perishable",
    "festive_relevant",
    "popularity_tier"
]

numeric_features = [
    col for col in features
    if col not in categorical_features
]

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

logistic_model = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", LogisticRegression(
        multi_class="multinomial",
        max_iter=1000
    ))
])

logistic_model.fit(X_train, y_train)

logistic_pred = logistic_model.predict(X_test)

print("Logistic Regression accuracy:",
      accuracy_score(y_test, logistic_pred))

print("\nClassification Report:")
print(classification_report(y_test, logistic_pred))

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

random_forest = Pipeline([
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        class_weight="balanced"
    ))
])

random_forest.fit(X_train, y_train)

rf_pred = random_forest.predict(X_test)

print("Random Forest accuracy:",
      accuracy_score(y_test, rf_pred))

print("\nClassification Report:")
print(classification_report(y_test, rf_pred))

"""## Model Comparison and Selection

| Model | Accuracy | Imminent Recall |
|---|---:|---:|
| Majority-Class Baseline | 62.28% | — |
| Logistic Regression | 92.52% | 76% |
| Random Forest | 93.04% | 62% |

Although Random Forest has slightly higher accuracy, Logistic Regression has higher recall for the **Imminent** class. Since the project specification focuses on recall for Imminent stockout cases, **Logistic Regression is selected as the preferred model**.

## Conclusion

The models were evaluated using a time-based train-test split. Logistic Regression achieved 92.52% accuracy and 76% recall for the Imminent class, while Random Forest achieved 93.04% accuracy and 62% Imminent recall.

Because the project prioritizes identifying Imminent stockout cases, Logistic Regression is selected as the preferred model.
"""